[package]
name = "htmx-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axohtml = "0.5.0"
axum = "0.6.20"
tokio = { version = "1.31.0", features = ["macros", "rt-multi-thread"] }
